Apache dashboard
newrelic/quickstarts-dashboard-library pull request #16
Opened 2021-04-20 10:27 UTC by JakubKotkowiak

2021-04-20 14:11 UTC, kidk requested changes
JSON looks good. I've added to small comments. 

Also when you take the screenshot of the dashboards, could you change the time range so it shows data on the whole graph? 

But besides that, everything looks great. Thanks 👍

2021-04-20 14:11 UTC, kidk commented on library/apache/config.yaml
> +    - Newrelic
`New Relic`

2021-04-20 14:11 UTC, kidk commented on library/apache/dashboards/apache.json
> +    "name": "Apache",
Could you manually move up the name and description field?

2021-04-21 07:21 UTC, JakubKotkowiak commented
> JSON looks good. I've added two small comments.
> 
> Also when you take the screenshot of the dashboards, could you change the time range so it shows data on the whole graph?
> 
> But besides that, everything looks great. Thanks 👍

The shortest it appears that I can go is 30 minutes, but yeah it's no problem.

2021-04-21 13:38 UTC, kidk approved these changes

2021-04-21 13:39 UTC, kidk commented
Looks good 👍

2021-04-21 15:32 UTC, merged